//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.22 at 05:13:42 PM TRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://springbootsoap.client.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.client.springbootsoap;
